#subs
s = 'CTATGGGCTATGGGACTATGGGTCATGGTTCATGGCATCTATGGGTCGCTATGGGCTATGGGCCCTATGGGGACCCCTATGGGCGCTATGGGCACTATGGGTGCGTCCGAGCCTATGGGTTGCAAGCAACTATGGGCCCTATGGGTACTATGGGTTTAGCTGCACACCTATGGGAACTATGGGCTATGGGAATAACCTATGGGCCGCCGCTAAGCTATGGGTTGCTATGGGCTATGGGGCTATGGGCTATGGGTCTCTATGGGGCTATGGGCTTCTATGGGCAGCTAGCCCGAACTATGGGCTATGGGATTTCTATGGGGTGCGGAAGTGCGAAAGGGACTATGGGTCTATGGGAAGTGCTATGGGCTATGGGAAGTTGGGGACTGGCTATGGGCGGCTGCCCTATGGGAAGAGCTATGGGTTGCTATGGGTTACCTATGGGTCCTATGGGACTATGGGGCCTATGGGAACGCACCATCTATGGGGAGTGAACTATGGGCGAAATGGCTATGGGCTATGGGGTGCTATCTTCTATGGGCTATGGGTCTATGGGCGCTATGGGCTATGGGACCTATGGGCTATGGGCTATGGGTACGTGTACCTATGGGACTATGGGGATCTATGGGTATAACTATGGGGAAGACTATGGGTTTCCGCCCTATGGGGTAATAGTAGGCTGCTATGGGACTATGGGGCGATCCCCTATGGGGCTATGGGGGTCTATGGGGACTATGGGTTCGACTCTATGGGCTATGGGACTATGGGACCTATGGGCCGGCGAGACTATGGGGTCACCTATGGGGAAAGGCTATGGGCTATGGGGTCCGGACTATGGGCGTAATCGTTCTATGGGTACCTATGGGGTGACCTTCTATGGGCCTATGGGCTATGGGCTATGGGCGCTATGGGCTGCTATGGGTCTATGGGAGCTATGGGCTATGGGCCTATGGGCTATGGGCCTATGGG'
t = 'CTATGGGCT'

locations = []
t_length = len(t)
for i in range(len(s) - t_length + 1):
    if s[i:i + t_length] == t:
        locations.append(i +1)

print(locations)  

#another method which works the same
locations =[]
start = 0
while start < len(s):
        index = s.find(t, start)
        if index == -1:
            break
        locations.append(index +1)
        start = index + 1

print(locations)